### PR TITLE
moved README file to /

### PR DESCRIPTION
**Pull request by FredrikAugust**
I simply moved the README file to the top dir so you can read it without going into one of the subdirectories

### CODE REVIEW

**Comment by PietPtr** [comment]
ugh fine

**Comment by FredrikAugust** [comment]
You do know you could've just declined it? I'm not the holy code police or something

Why Can I Edit This Comment If Eyes Aren't Real?

**Comment by PietPtr** [comment]
Nah it's an nice idea

**Comment by raatmarien** [comment]
Code police checking in, we approve.

EDITEDITEDITEDITEDITEDITEDITEDITEDITEDIT

WTF I'M NOT SAYING THIS
#modabuse

**Comment by PietPtr** [comment]
Phew

**Comment by FredrikAugust** [comment]
[Aaand it's a great way to stay in shape](http://www.youtube.com/watch?v=_Bh2hv1NGJo)

**Pull request merged**
